language: node_js

node_js:
  - v6

brances:
  only:
    - master

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'electrode-electrify' ]; then cd .. && eval "mv $currentfolder electrode-electrify" && cd electrode-electrify; fi

script:
  - npm run test
